### PR TITLE
Error details & Generator improvements

### PR DESCRIPTION
**Pull request by sherbang**
So I started with some more improvements to providing error details in exceptions, then I got carried away and did a bunch of work on the generator.

Changes include:
- Add more checks to ruff (and related code changes)
- Parsing the error that Manage returns when you try to create an object that already exists
- Moving generator templates out into separate files so code highlighting works
- Move generator out of pyconnectwise namespace, so it isn't included with the shipped library
- Document how to run the generator
- Glued together the different parts of the generator, so it all runs in one go (model gen, schema cleanup, endpoint gen)
- Changed line-length in our tooling to match what the generator puts out
- Make sure that we don't generate endpoints that refer to models that don't exist (fail faster)

I _think_ that's everything worth mentioning.  Now I've got to figure out/remember what started me on this journey in the first place. 😁

### CODE REVIEW

**Comment by sherbang** [comment]
Nice automation!

**Comment by sherbang** [comment]
I pushed a few more commits today.  The most notable one is lazy-loading endpoints.

Before the lazy-loading endpoints change:
`python -c 'import pyconnectwise'` would take 2.8 seconds to run and use ~240Mb of memory.

After the change:
`python -c 'import pyconnectwise'` takes 136 milliseconds to run and use ~50Mb of memory.

**Comment by Yoshify** [comment]
This PR is fantastic - I love the additions to lazy loading the imports. I still have more testing I'd like to do with it (with generating Automate files especially) but other than that I can't see any downsides to this. I expect to merge soon.

**Review by Yoshify — APPROVED** [review]
LGTM

**Comment by Yoshify** [comment]
Merged - thanks again for your incredible contribution!

**Pull request merged**
